CREATE TABLE IDS (
  TABLE_NAME varchar(20) NOT NULL COMMENT '테이블명',
  NEXT_ID decimal(30,0) NOT NULL DEFAULT '0' COMMENT '다음ID',
  PRIMARY KEY (TABLE_NAME)
) ;



CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL COMMENT '분류코드',
  CL_CODE_NM varchar(60) DEFAULT NULL COMMENT '분류코드명',
  CL_CODE_DC varchar(200) DEFAULT NULL COMMENT '분류코드설명',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (CL_CODE)
) ;



CREATE TABLE LETTCCMMNCODE (
  CODE_ID varchar(6) NOT NULL COMMENT '코드ID',
  CODE_ID_NM varchar(60) DEFAULT NULL COMMENT '코드ID명',
  CODE_ID_DC varchar(200) DEFAULT NULL COMMENT '코드ID설명',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  CL_CODE char(3) DEFAULT NULL COMMENT '분류코드',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (CODE_ID),
  KEY R_179 (CL_CODE),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ;



CREATE TABLE LETTCCMMNDETAILCODE (
  CODE_ID varchar(6) NOT NULL COMMENT '코드ID',
  CODE varchar(15) NOT NULL COMMENT '코드',
  CODE_NM varchar(60) DEFAULT NULL COMMENT '코드명',
  CODE_DC varchar(200) DEFAULT NULL COMMENT '코드설명',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ;



CREATE TABLE LETTNORGNZTINFO (
  ORGNZT_ID char(20) NOT NULL DEFAULT '' COMMENT '조직ID',
  ORGNZT_NM varchar(20) NOT NULL COMMENT '조직명',
  ORGNZT_DC varchar(100) DEFAULT NULL COMMENT '조직설명',
  PRIMARY KEY (ORGNZT_ID)
) ;



CREATE TABLE LETTNAUTHORGROUPINFO (
  GROUP_ID char(20) NOT NULL DEFAULT '' COMMENT '그룹ID',
  GROUP_NM varchar(60) NOT NULL COMMENT '그룹명',
  GROUP_CREAT_DE char(20) NOT NULL COMMENT '그룹생성일',
  GROUP_DC varchar(100) DEFAULT NULL COMMENT '그룹설명',
  PRIMARY KEY (GROUP_ID)
) ;



CREATE TABLE LETTNAUTHORINFO (
  AUTHOR_CODE varchar(30) NOT NULL DEFAULT '' COMMENT '권한코드',
  AUTHOR_NM varchar(60) NOT NULL COMMENT '권한명',
  AUTHOR_DC varchar(200) DEFAULT NULL COMMENT '권한설명',
  AUTHOR_CREAT_DE char(20) NOT NULL COMMENT '권한생성일',
  PRIMARY KEY (AUTHOR_CODE)
) ;



CREATE TABLE LETTNROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL COMMENT '부모롤',
  CHLDRN_ROLE varchar(30) NOT NULL COMMENT '자식롤',
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  KEY R_308 (CHLDRN_ROLE),
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;



CREATE TABLE LETTNROLEINFO (
  ROLE_CODE varchar(50) NOT NULL DEFAULT '' COMMENT '롤코드',
  ROLE_NM varchar(60) NOT NULL COMMENT '롤명',
  ROLE_PTTRN varchar(300) DEFAULT NULL COMMENT '롤패턴',
  ROLE_DC varchar(200) DEFAULT NULL COMMENT '롤설명',
  ROLE_TY varchar(80) DEFAULT NULL COMMENT '롤유형',
  ROLE_SORT varchar(10) DEFAULT NULL COMMENT '롤정렬순서',
  ROLE_CREAT_DE char(20) NOT NULL COMMENT '롤생성일',
  PRIMARY KEY (ROLE_CODE)
) ;



CREATE TABLE LETTNAUTHORROLERELATE (
  AUTHOR_CODE varchar(30) NOT NULL COMMENT '권한코드',
  ROLE_CODE varchar(50) NOT NULL COMMENT '롤코드',
  CREAT_DT datetime DEFAULT NULL COMMENT '생성일시',
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  KEY R_292 (ROLE_CODE),
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES LETTNROLEINFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;



CREATE TABLE LETTNGNRLMBER (
  MBER_ID varchar(20) NOT NULL DEFAULT '' COMMENT '회원ID',
  PASSWORD varchar(200) NOT NULL COMMENT '비밀번호',
  PASSWORD_HINT varchar(100) NOT NULL COMMENT '비밀번호힌트',
  PASSWORD_CNSR varchar(100) NOT NULL COMMENT '비밀번호정답',
  IHIDNUM varchar(200) DEFAULT NULL COMMENT '주민등록번호',
  MBER_NM varchar(50) NOT NULL COMMENT '회원명',
  ZIP varchar(6) DEFAULT NULL COMMENT '우편번호',
  ADRES varchar(100) DEFAULT NULL COMMENT '주소',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  MBER_STTUS varchar(15) DEFAULT NULL COMMENT '회원상태',
  DETAIL_ADRES varchar(100) DEFAULT NULL COMMENT '상세주소',
  END_TELNO varchar(4) DEFAULT NULL COMMENT '끝전화번호',
  MBTLNUM varchar(20) DEFAULT NULL COMMENT '이동전화번호',
  GROUP_ID char(20) DEFAULT NULL COMMENT '그룹ID',
  MBER_FXNUM varchar(20) DEFAULT NULL COMMENT '팩스번호',
  MBER_EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '이메일주소',
  MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '중간전화번호',
  SBSCRB_DE datetime DEFAULT NULL COMMENT '가입일',
  SEXDSTN_CODE char(1) DEFAULT NULL COMMENT '성별코드',
  ESNTL_ID char(20) NOT NULL COMMENT '고유ID',
  PRIMARY KEY (MBER_ID),
  KEY LETTNGNRLMBER_ibfk_1 (GROUP_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;



CREATE TABLE LETTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(20) NOT NULL COMMENT '보안설정대상ID',
  MBER_TY_CODE varchar(15) DEFAULT NULL COMMENT '회원유형코드',
  AUTHOR_CODE varchar(30) NOT NULL COMMENT '권한코드',
  PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  KEY LETTNEMPLYRSCRTYESTBS_ibfk_4 (AUTHOR_CODE),
  CONSTRAINT LETTNEMPLYRSCRTYESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE)
) ;



CREATE TABLE LETTNTMPLATINFO (
  TMPLAT_ID char(20) NOT NULL DEFAULT '' COMMENT '템플릿ID',
  TMPLAT_NM varchar(255) DEFAULT NULL COMMENT '템플릿명',
  TMPLAT_COURS varchar(2000) DEFAULT NULL COMMENT '템플릿경로',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  TMPLAT_SE_CODE char(6) DEFAULT NULL COMMENT '템플릿구분코드',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (TMPLAT_ID)
) ;



CREATE TABLE LETTNBBSMASTER (
  BBS_ID char(20) NOT NULL COMMENT '게시판ID',
  BBS_NM varchar(255) NOT NULL COMMENT '게시판명',
  BBS_INTRCN varchar(2400) DEFAULT NULL COMMENT '게시판소개',
  BBS_TY_CODE char(6) NOT NULL COMMENT '게시판유형코드',
  BBS_ATTRB_CODE char(6) NOT NULL COMMENT '게시판속성코드',
  REPLY_POSBL_AT char(1) DEFAULT NULL COMMENT '답글가능여부',
  FILE_ATCH_POSBL_AT char(1) NOT NULL COMMENT '파일첨부가능여부',
  ATCH_POSBL_FILE_NUMBER decimal(2,0) NOT NULL COMMENT '첨부가능파일개수',
  ATCH_POSBL_FILE_SIZE decimal(8,0) DEFAULT NULL COMMENT '첨부가능파일크기',
  USE_AT char(1) NOT NULL COMMENT '사용여부',
  TMPLAT_ID char(20) DEFAULT NULL COMMENT '템플릿ID',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  FRST_REGIST_PNTTM datetime NOT NULL COMMENT '최초등록시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (BBS_ID)
) ;



CREATE TABLE LETTNBBSUSE (
  BBS_ID char(20) NOT NULL COMMENT '게시판ID',
  TRGET_ID char(20) NOT NULL DEFAULT '' COMMENT '대상ID',
  USE_AT char(1) NOT NULL COMMENT '사용여부',
  REGIST_SE_CODE char(6) DEFAULT NULL COMMENT '등록구분코드',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;



CREATE TABLE LETTNBBS (
  NTT_ID decimal(20,0) NOT NULL COMMENT '게시글ID',
  BBS_ID char(20) NOT NULL COMMENT '게시판ID',
  NTT_NO decimal(20,0) DEFAULT NULL COMMENT '게시글번호',
  NTT_SJ varchar(2000) DEFAULT NULL COMMENT '게시글제목',
  NTT_CN mediumtext COMMENT '게시글내용',
  ANSWER_AT char(1) DEFAULT NULL COMMENT '답변여부',
  PARNTSCTT_NO decimal(10,0) DEFAULT NULL COMMENT '부모글번호',
  ANSWER_LC int(8) DEFAULT NULL COMMENT '답변위치',
  SORT_ORDR decimal(8,0) DEFAULT NULL COMMENT '정렬순서',
  RDCNT decimal(10,0) DEFAULT NULL COMMENT '조회수',
  USE_AT char(1) NOT NULL COMMENT '사용여부',
  NTCE_BGNDE char(20) DEFAULT NULL COMMENT '게시시작일',
  NTCE_ENDDE char(20) DEFAULT NULL COMMENT '게시종료일',
  NTCR_ID varchar(20) DEFAULT NULL COMMENT '게시자ID',
  NTCR_NM varchar(20) DEFAULT NULL COMMENT '게시자명',
  PASSWORD varchar(200) DEFAULT NULL COMMENT '비밀번호',
  ATCH_FILE_ID char(20) DEFAULT NULL COMMENT '첨부파일ID',
  FRST_REGIST_PNTTM datetime NOT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (NTT_ID,BBS_ID),
  KEY LETTNBBS_ibfk_1 (BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;



CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) NOT NULL DEFAULT '' COMMENT '게시판ID',
  ANSWER_AT char(1) NOT NULL DEFAULT '' COMMENT '댓글여부',
  STSFDG_AT char(1) NOT NULL DEFAULT '' COMMENT '만족도여부',
  FRST_REGIST_PNTTM datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '최초등록시점', 
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  FRST_REGISTER_ID varchar(20) NOT NULL DEFAULT '' COMMENT '최초등록자ID',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (BBS_ID)
) ;



CREATE TABLE LETTNEMPLYRINFO (
  EMPLYR_ID varchar(20) NOT NULL COMMENT '업무사용자ID',
  ORGNZT_ID char(20) DEFAULT NULL COMMENT '조직ID',
  USER_NM varchar(60) NOT NULL COMMENT '사용자명',
  PASSWORD varchar(200) NOT NULL COMMENT '비밀번호',
  EMPL_NO varchar(20) DEFAULT NULL COMMENT '사원번호',
  IHIDNUM varchar(200) DEFAULT NULL COMMENT '주민등록번호',
  SEXDSTN_CODE char(1) DEFAULT NULL COMMENT '성별코드',
  BRTHDY char(20) DEFAULT NULL COMMENT '생년월일',
  FXNUM varchar(20) DEFAULT NULL COMMENT '팩스번호',
  HOUSE_ADRES varchar(100) DEFAULT NULL COMMENT '자택주소',
  PASSWORD_HINT varchar(100) NOT NULL COMMENT '비밀번호힌트',
  PASSWORD_CNSR varchar(100) NOT NULL COMMENT '비밀번호정답',
  HOUSE_END_TELNO varchar(4) DEFAULT NULL COMMENT '자택끝전화번호',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  DETAIL_ADRES varchar(100) DEFAULT NULL COMMENT '상세주소',
  ZIP varchar(6) DEFAULT NULL COMMENT '우편번호',
  OFFM_TELNO varchar(20) DEFAULT NULL COMMENT '사무실전화번호',
  MBTLNUM varchar(20) DEFAULT NULL COMMENT '이동전화번호',
  EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '이메일주소',
  OFCPS_NM varchar(60) DEFAULT NULL COMMENT '직위명',
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '자택중간전화번호',
  GROUP_ID char(20) DEFAULT NULL COMMENT '그룹ID',
  PSTINST_CODE char(8) DEFAULT NULL COMMENT '소속기관코드',
  EMPLYR_STTUS_CODE varchar(15) NOT NULL COMMENT '사용자상태코드',
  ESNTL_ID char(20) NOT NULL COMMENT '고유ID',
  CRTFC_DN_VALUE varchar(20) DEFAULT NULL COMMENT '인증DN값',
  SBSCRB_DE datetime DEFAULT NULL COMMENT '가입일',
  PRIMARY KEY (EMPLYR_ID),
  KEY LETTNEMPLYRINFO_ibfk_2 (GROUP_ID),
  KEY LETTNEMPLYRINFO_ibfk_1 (ORGNZT_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;



CREATE TABLE LETTCZIP (
  ZIP varchar(6) NOT NULL COMMENT '우편번호',
  SN decimal(10,0) NOT NULL DEFAULT '0' COMMENT '일련번호',
  CTPRVN_NM varchar(20) DEFAULT NULL COMMENT '시도명',
  SIGNGU_NM varchar(20) DEFAULT NULL COMMENT '시군구명',
  EMD_NM varchar(60) DEFAULT NULL COMMENT '읍면동명',
  LI_BULD_NM varchar(60) DEFAULT NULL COMMENT '법정동건물명',
  LNBR_DONG_HO varchar(20) DEFAULT NULL COMMENT '번지동호',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (ZIP,SN)
) ;



CREATE TABLE LETTNBANNER (
  BANNER_ID char(20) NOT NULL DEFAULT '' COMMENT '배너ID',
  BANNER_NM varchar(60) NOT NULL COMMENT '배너명',
  LINK_URL varchar(255) NOT NULL COMMENT '링크URL',
  BANNER_IMAGE varchar(60) NOT NULL COMMENT '배너이미지',
  BANNER_DC varchar(200) DEFAULT NULL COMMENT '배너설명',
  REFLCT_AT char(1) NOT NULL COMMENT '반영여부',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  BANNER_IMAGE_FILE varchar(60) DEFAULT NULL COMMENT '배너이미지파일',
  SORT_ORDR decimal(8,0) DEFAULT NULL COMMENT '정렬순서',
  PRIMARY KEY (BANNER_ID)
) ;



CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(20) NOT NULL DEFAULT '' COMMENT '기업회원ID',
  ENTRPRS_SE_CODE char(15) DEFAULT NULL COMMENT '기업구분코드',
  BIZRNO varchar(10) DEFAULT NULL COMMENT '사업자등록번호',
  JURIRNO varchar(13) DEFAULT NULL COMMENT '법인등록번호',
  CMPNY_NM varchar(60) NOT NULL COMMENT '회사명',
  CXFC varchar(50) DEFAULT NULL COMMENT '대표자명',
  ZIP varchar(6) DEFAULT NULL COMMENT '우편번호',
  ADRES varchar(100) DEFAULT NULL COMMENT '주소',
  ENTRPRS_MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '기업중간전화번호',
  FXNUM varchar(20) DEFAULT NULL COMMENT '팩스번호',
  INDUTY_CODE char(15) DEFAULT NULL COMMENT '업종코드',
  APPLCNT_NM varchar(50) DEFAULT NULL COMMENT '신청자명',
  APPLCNT_IHIDNUM varchar(200) DEFAULT NULL COMMENT '신청자주민등록번호',
  SBSCRB_DE datetime DEFAULT NULL COMMENT '가입일',
  ENTRPRS_MBER_STTUS varchar(15) DEFAULT NULL COMMENT '기업회원상태',
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL COMMENT '기업회원비밀번호',
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL COMMENT '기업회원비밀번호힌트',
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL COMMENT '기업회원비밀번호정답',
  GROUP_ID char(20) DEFAULT NULL COMMENT '그룹ID',
  DETAIL_ADRES varchar(100) DEFAULT NULL COMMENT '상세주소',
  ENTRPRS_END_TELNO varchar(4) DEFAULT NULL COMMENT '기업끝전화번호',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  APPLCNT_EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '신청자이메일주소',
  ESNTL_ID char(20) NOT NULL COMMENT '고유ID',
  PRIMARY KEY (ENTRPRS_MBER_ID),
  KEY LETTNENTRPRSMBER_ibfk_1 (GROUP_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;



CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL COMMENT '첨부파일ID',
  CREAT_DT datetime NOT NULL COMMENT '생성일시',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  PRIMARY KEY (ATCH_FILE_ID)
) ;



CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL COMMENT '첨부파일ID',
  FILE_SN decimal(10,0) NOT NULL COMMENT '파일일련번호',
  FILE_STRE_COURS varchar(2000) NOT NULL COMMENT '파일저장경로',
  STRE_FILE_NM varchar(255) NOT NULL COMMENT '저장파일명',
  ORIGNL_FILE_NM varchar(255) DEFAULT NULL COMMENT '원본파일명',
  FILE_EXTSN varchar(20) NOT NULL COMMENT '파일확장자',
  FILE_CN mediumtext COMMENT '파일내용',
  FILE_SIZE decimal(8,0) DEFAULT NULL COMMENT '파일크기',
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;



CREATE TABLE LETTNFAQINFO (
  FAQ_ID char(20) NOT NULL COMMENT 'FAQ ID',
  QESTN_SJ varchar(255) DEFAULT NULL COMMENT '질문제목',
  QESTN_CN varchar(2500) DEFAULT NULL COMMENT '질문내용',
  ANSWER_CN varchar(2500) DEFAULT NULL COMMENT '답변내용',
  RDCNT decimal(10,0) DEFAULT NULL COMMENT '조회수',
  FRST_REGIST_PNTTM datetime NOT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime NOT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) NOT NULL COMMENT '최종수정자ID',
  ATCH_FILE_ID char(20) DEFAULT NULL COMMENT '첨부파일ID',
  QNA_PROCESS_STTUS_CODE char(1) DEFAULT NULL COMMENT 'QNA처리상태코드',
  PRIMARY KEY (FAQ_ID),
  KEY R_298 (ATCH_FILE_ID),
  CONSTRAINT LETTNFAQINFO_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;




CREATE TABLE LETTNINDVDLINFOPOLICY (
  INDVDL_INFO_POLICY_ID char(20) NOT NULL DEFAULT '' COMMENT '개인정보보호방침ID',
  INDVDL_INFO_POLICY_CN varchar(2500) DEFAULT NULL COMMENT '개인정보보호방침내용',
  INDVDL_INFO_POLICY_AGRE_AT char(1) DEFAULT NULL COMMENT '개인정보보호방침동의여부',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  INDVDL_INFO_POLICY_NM varchar(255) DEFAULT NULL COMMENT '개인정보보호방침명',
  PRIMARY KEY (INDVDL_INFO_POLICY_ID)
) ;



CREATE TABLE LETTNPROGRMLIST (
  PROGRM_FILE_NM varchar(60) NOT NULL DEFAULT '' COMMENT '프로그램파일명',
  PROGRM_STRE_PATH varchar(100) NOT NULL COMMENT '프로그램저장경로',
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL COMMENT '프로그램한글명',
  PROGRM_DC varchar(200) DEFAULT NULL COMMENT '프로그램설명',
  URL varchar(100) NOT NULL COMMENT 'URL',
  PRIMARY KEY (PROGRM_FILE_NM)
) ;



CREATE TABLE LETTNMENUINFO (
  MENU_NM varchar(60) NOT NULL COMMENT '메뉴명',
  PROGRM_FILE_NM varchar(60) NOT NULL COMMENT '프로그램파일명',
  MENU_NO decimal(20,0) NOT NULL COMMENT '메뉴번호',
  UPPER_MENU_NO decimal(20,0) DEFAULT NULL COMMENT '상위메뉴번호',
  MENU_ORDR decimal(5,0) NOT NULL COMMENT '메뉴순서',
  MENU_DC varchar(250) DEFAULT NULL COMMENT '메뉴설명',
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL COMMENT '관련이미지경로',
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL COMMENT '관련이미지명',
  PRIMARY KEY (MENU_NO),
  KEY R_2 (PROGRM_FILE_NM),
  KEY R_4 (UPPER_MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES LETTNPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;



CREATE TABLE LETTNMENUCREATDTLS (
  MENU_NO decimal(20,0) NOT NULL COMMENT '메뉴번호',
  AUTHOR_CODE varchar(30) NOT NULL COMMENT '권한코드',
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL COMMENT '매핑생성ID',
  PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  KEY R_247 (MAPNG_CREAT_ID),
  KEY R_303 (AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO) ON DELETE CASCADE
) ;




CREATE TABLE LETTNQAINFO (
  QA_ID char(20) NOT NULL COMMENT 'QA ID',
  QESTN_SJ varchar(255) DEFAULT NULL COMMENT '질문제목',
  QESTN_CN varchar(2500) DEFAULT NULL COMMENT '질문내용',
  WRITNG_DE char(20) DEFAULT NULL COMMENT '작성일',
  RDCNT decimal(10,0) DEFAULT NULL COMMENT '조회수',
  EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '이메일주소',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  QNA_PROCESS_STTUS_CODE char(1) DEFAULT NULL COMMENT 'QNA처리상태코드',
  WRTER_NM varchar(20) DEFAULT NULL COMMENT '작성자명',
  ANSWER_CN varchar(2500) DEFAULT NULL COMMENT '답변내용',
  WRITNG_PASSWORD varchar(20) DEFAULT NULL COMMENT '작성비밀번호',
  ANSWER_DE char(20) DEFAULT NULL COMMENT '답변일',
  EMAIL_ANSWER_AT char(1) DEFAULT NULL COMMENT '이메일답변여부',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '중간전화번호',
  END_TELNO varchar(4) DEFAULT NULL COMMENT '끝전화번호',
  PRIMARY KEY (QA_ID)
) ;



CREATE TABLE LETTNQUSTNRTMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL COMMENT '설문지템플릿ID',
  QUSTNR_TMPLAT_TY varchar(100) DEFAULT NULL COMMENT '설문지템플릿유형',
  QUSTNR_TMPLAT_DC varchar(2000) DEFAULT NULL COMMENT '설문지템플릿설명',
  QUSTNR_TMPLAT_PATH_NM varchar(100) DEFAULT NULL COMMENT '설문지템플릿경로명',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  QUSTNR_TMPLAT_IMAGE_INFO blob COMMENT '설문지템플릿이미지정보',
  PRIMARY KEY (QUSTNR_TMPLAT_ID)
) ;



CREATE TABLE LETTNQESTNRINFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL COMMENT '설문지템플릿ID',
  QESTNR_ID char(20) NOT NULL COMMENT '설문조사ID',
  QUSTNR_SJ varchar(255) DEFAULT NULL COMMENT '설문조사제목',
  QUSTNR_PURPS varchar(1000) DEFAULT NULL COMMENT '설문조사목적',
  QUSTNR_WRITNG_GUIDANCE_CN varchar(2000) DEFAULT NULL COMMENT '설문조사작성안내내용',
  QUSTNR_TRGET varchar(1000) DEFAULT NULL COMMENT '설문조사대상',
  QUSTNR_BGNDE char(20) CHARACTER SET latin1 DEFAULT NULL COMMENT '설문조사시작일',
  QUSTNR_ENDDE char(20) DEFAULT NULL COMMENT '설문조사종료일',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
  CONSTRAINT LETTNQESTNRINFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID) REFERENCES LETTNQUSTNRTMPLAT (QUSTNR_TMPLAT_ID)
) ;



CREATE TABLE LETTNQUSTNRQESITM (
  QESTNR_ID char(20) NOT NULL COMMENT '설문조사ID',
  QUSTNR_QESITM_ID char(20) NOT NULL COMMENT '설문조사문항ID',
  QUSTNR_TMPLAT_ID char(20) NOT NULL COMMENT '설문지템플릿ID',
  QESTN_SN decimal(10,0) DEFAULT NULL COMMENT '질문일련번호',
  QESTN_TY_CODE char(1) DEFAULT NULL COMMENT '질문유형코드',
  QESTN_CN varchar(2500) DEFAULT NULL COMMENT '질문내용',
  MXMM_CHOISE_CO decimal(5,0) DEFAULT NULL COMMENT '최대선택개수',
  FRST_REGIST_PNTTM datetime NOT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime NOT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) NOT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  KEY R_11 (QUSTNR_TMPLAT_ID,QESTNR_ID),
  CONSTRAINT LETTNQUSTNRQESITM_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES LETTNQESTNRINFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;



CREATE TABLE LETTNQUSTNRIEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL COMMENT '설문지템플릿ID',
  QESTNR_ID char(20) NOT NULL COMMENT '설문조사ID',
  QUSTNR_QESITM_ID char(20) NOT NULL COMMENT '설문조사문항ID',
  QUSTNR_IEM_ID varchar(20) NOT NULL COMMENT '설문조사항목ID',
  IEM_SN decimal(5,0) DEFAULT NULL COMMENT '항목일련번호',
  IEM_CN varchar(1000) DEFAULT NULL COMMENT '항목내용',
  ETC_ANSWER_AT char(1) DEFAULT NULL COMMENT '기타답변여부',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
  KEY R_9 (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT LETTNQUSTNRIEM_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES LETTNQUSTNRQESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;




CREATE TABLE LETTNQUSTNRRESPONDINFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL COMMENT '설문지템플릿ID',
  QESTNR_ID char(20) NOT NULL COMMENT '설문조사ID',
  QUSTNR_RESPOND_ID char(20) NOT NULL COMMENT '설문조사응답자ID',
  SEXDSTN_CODE char(1) DEFAULT NULL COMMENT '성별코드',
  OCCP_TY_CODE varchar(1) DEFAULT NULL COMMENT '직업유형코드',
  RESPOND_NM varchar(50) DEFAULT NULL COMMENT '응답자명',
  BRTHDY char(20) DEFAULT NULL COMMENT '생년월일',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '중간전화번호',
  END_TELNO varchar(4) DEFAULT NULL COMMENT '끝전화번호',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
  CONSTRAINT LETTNQUSTNRRESPONDINFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES LETTNQESTNRINFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;



CREATE TABLE LETTNQUSTNRRSPNSRESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL COMMENT '설문조사응답결과ID',
  QESTNR_ID char(20) NOT NULL COMMENT '설문조사ID',
  QUSTNR_QESITM_ID char(20) NOT NULL COMMENT '설문조사문항ID',
  QUSTNR_TMPLAT_ID char(20) NOT NULL COMMENT '설문지템플릿ID',
  RESPOND_ANSWER_CN varchar(1000) DEFAULT NULL COMMENT '응답자답변내용',
  ETC_ANSWER_CN varchar(1000) DEFAULT NULL COMMENT '기타답변내용',
  RESPOND_NM varchar(50) DEFAULT NULL COMMENT '응답자명',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  QUSTNR_IEM_ID varchar(20) DEFAULT NULL COMMENT '설문조사항목ID',
  PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  KEY R_306 (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT LETTNQUSTNRRSPNSRESULT_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES LETTNQUSTNRQESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;



CREATE TABLE LETTNSTPLATINFO (
  USE_STPLAT_ID char(20) NOT NULL COMMENT '이용약관ID',
  USE_STPLAT_NM varchar(100) DEFAULT NULL COMMENT '이용약관명',
  USE_STPLAT_CN mediumtext COMMENT '이용약관내용',
  INFO_PROVD_AGRE_CN mediumtext COMMENT '정보제공동의내용',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (USE_STPLAT_ID)
) ;

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;